"use client";

import React, { forwardRef } from "react";
import ReactMarkdown from "react-markdown";
import { BirthData, ChartResponse, CycleResponse } from "@/lib/api";
import BaziChart from "@/components/BaziChart";

interface ExportTemplateProps {
    userName: string;
    birthData: BirthData;
    type: "chart" | "analysis" | "oracle";
    content?: string | ChartResponse; // content for analysis/chart
    cycleData?: CycleResponse | null; // for chart
    title?: string; // Analysis Topic or "八字排盘"
    qrCodeUrl?: string; // Optional QR code for sharing
}

const ExportTemplate = forwardRef<HTMLDivElement, ExportTemplateProps>(
    ({ userName, birthData, type, content, cycleData, title, qrCodeUrl }, ref) => {

        // Formatting Date
        const date = new Date();
        const dateStr = `${date.getFullYear()}年${date.getMonth() + 1}月${date.getDate()}日`;

        return (
            <div
                ref={ref}
                className="w-[800px] min-h-[1200px] bg-[#F8F8F0] relative text-[#1A1A1A] font-serif overflow-hidden"
                style={{ padding: "60px 50px" }}
            >
                {/* === Aesthetic Background === */}
                {/* Texture Overlay (CSS handled globally or inline if needed) */}
                <div className="absolute inset-0 opacity-10 pointer-events-none"
                    style={{ backgroundImage: "url('/texture/rice-paper.png')" }}></div>

                {/* Classical Border */}
                <div className="absolute inset-4 border-4 border-double border-[#B8860B]/30 pointer-events-none rounded-2xl"></div>
                <div className="absolute inset-3 border border-[#B8860B]/10 pointer-events-none rounded-[18px]"></div>

                {/* Corner Decor (Simple CSS Shapes for now) */}
                <div className="absolute top-8 left-8 w-4 h-4 border-t-2 border-l-2 border-[#B8860B]/50"></div>
                <div className="absolute top-8 right-8 w-4 h-4 border-t-2 border-r-2 border-[#B8860B]/50"></div>
                <div className="absolute bottom-8 left-8 w-4 h-4 border-b-2 border-l-2 border-[#B8860B]/50"></div>
                <div className="absolute bottom-8 right-8 w-4 h-4 border-b-2 border-r-2 border-[#B8860B]/50"></div>

                {/* === Header === */}
                <div className="text-center mb-10 relative z-10">
                    <div className="inline-block px-4 py-1 mb-4 border-b border-[#B8860B]/20 text-[#B8860B]/60 text-xs tracking-[0.3em] uppercase">
                        命理大师 · {type === 'chart' ? '命盘' : type === 'oracle' ? '卜卦' : '分析'}
                    </div>
                    <h1 className="text-3xl font-song font-bold text-[#1A1A1A] tracking-widest mb-4">
                        {title || (type === "chart" ? "八字排盘" : "命理分析报告")}
                    </h1>
                    <div className="flex items-center justify-center gap-6 text-sm text-[#1A1A1A]/60 font-song">
                        <span>{userName}</span>
                        <span>·</span>
                        <span>{birthData.gender === '男' ? '乾造' : '坤造'}</span>
                        <span>·</span>
                        <span>{birthData.birth_year}年{birthData.month}月{birthData.day}日 {birthData.hour}时</span>
                    </div>
                </div>

                {/* === Content Body === */}
                <div className="relative z-10 min-h-[800px]">

                    {/* VARIANT: CHART */}
                    {type === "chart" && content && typeof content !== 'string' && (
                        <div className="space-y-8 origin-top scale-[0.95]">
                            <BaziChart data={content as ChartResponse} cycleData={cycleData} />
                        </div>
                    )}

                    {/* VARIANT: ANALYSIS / TEXT */}
                    {(type === "analysis" || type === "oracle") && typeof content === 'string' && (
                        <div className="prose prose-stone max-w-none prose-p:text-[#1A1A1A]/80 prose-headings:text-[#B8860B] prose-headings:font-song">
                            <ReactMarkdown>{content}</ReactMarkdown>
                        </div>
                    )}

                </div>

                {/* === Footer === */}
                <div className="mt-12 pt-6 border-t border-[#1A1A1A]/5 flex items-end justify-between relative z-10">
                    <div className="text-xs text-[#1A1A1A]/40 space-y-1">
                        <p>Generated by Fortune Teller AI</p>
                        <p>推演日期：{dateStr}</p>
                    </div>
                    {qrCodeUrl && (
                        <div className="bg-white p-2 border border-[#1A1A1A]/10">
                            {/* Placeholder for QR Code */}
                            <div className="w-16 h-16 bg-[#1A1A1A]/5 flex items-center justify-center text-[10px] text-[#1A1A1A]/20">
                                QR Code
                            </div>
                        </div>
                    )}
                </div>
            </div>
        );
    }
);

ExportTemplate.displayName = "ExportTemplate";
export default ExportTemplate;
